env: "dev"

mongo_config:
  db_name: "GRPCMicroservicesCluster"
  conn_string: "mongodb+srv://%s:%s@grpcmicroservicescluste.6q1e9je.mongodb.net/?retryWrites=true&w=majority"
  collections:
    family: "family"
    invite: "invite"
    sequence: "sequence"

clients_config:
  sso:
    address: "droplet.senkevichdev.work:44044"
    timeout: 5s
    retries_count: 5

grpc:
  port: 33033
  timeout: 5s